- .gitignore
- Makefile
- api/v1beta1/swift_types.go
- hack/clean_local_webhook.sh
- hack/configure_local_webhook.sh
- main.go
Adds the local webhooks pattern used across all our operator
> Local webhooks support

- .pre-commit-config.yaml
> Add pre-commit for swift

- api/v1beta1/swiftproxy_types.go
- config/crd/bases/swift.openstack.org_swiftproxies.yaml
- config/crd/bases/swift.openstack.org_swifts.yaml
- config/samples/swift_v1beta1_swift.yaml
- config/samples/swift_v1beta1_swiftproxy.yaml
- fixing passwordSelectors field
- removing unused transportUrl from the PasswordSelectors
- adding defaults to sample configs for standalone testing
> Fix PasswordSelectors and update sample configs

- Makefile
Just updating to be in-line with other operator `Makefile`s
> Use podman instead of docker in Makefile

- config/samples/swift_v1beta1_swift.yaml
- config/samples/swift_v1beta1_swiftproxy.yaml
- config/samples/swift_v1beta1_swiftring.yaml
- config/samples/swift_v1beta1_swiftstorage.yaml
- config/samples/swiftclient.yaml
Jira: [OSP-30111](https://issues.redhat.com//browse/OSP-30111)
> Drop container images from config/samples

- Makefile
inject DEFAULT_IMG
pin operator-sdk to use local/bin version
> Standardize makefile

- Makefile
sync Makefile changes from skeleton (operator-sdk init)
> syncronize operator-sdk in Makefile

- controllers/swiftproxy_controller.go
- controllers/swiftstorage_controller.go
- pkg/swiftproxy/deployment.go
- pkg/swiftstorage/statefulset.go
NetworkAttachments won't work without these.
> Add missing networkattachment annotations

- Dockerfile
Set CGO_ENABLED=1 using extra args and use the ubi-minimal image to make this operator FIPS compliant according to the check-payload tool[1].
[1] https://github.com/openshift/check-payload
> Make swift-operator image FIPS-compliant

- .prow_ci.env
- Makefile
- config/manifests/bases/swift-operator.clusterserviceversion.yaml
Also update the prow environment and Makefile.
> Set FIPS feature annotation in the CSV

- controllers/swift_controller.go
- controllers/swiftproxy_controller.go
- controllers/swiftstorage_controller.go
Noticed a couple of wrong return values, fixing them
> Fix return values

- pkg/swiftring/funcs.go
- pkg/swiftring/volumes.go
- templates/swiftring/bin/swift-ring-tool
Fixes a possible race condition and two minor issues.
> Fix ring job

- controllers/swiftstorage_controller.go
SwiftStorage status was set to Ready before the network attachments were created. This could result in a deployment with missing network attachments.
At the same time add missing status defer function.
> Fix status issue and ensure NetworkAttachments are created

- config/rbac/role.yaml
- controllers/swiftproxy_controller.go
- controllers/swiftstorage_controller.go
- pkg/swift/funcs.go
- pkg/swiftproxy/templates.go
- pkg/swiftstorage/templates.go
- templates/swiftproxy/config/00-proxy-server.conf
- templates/swiftstorage/config/00-account-server.conf
- templates/swiftstorage/config/00-container-server.conf
- templates/swiftstorage/config/00-object-server.conf
- tests/functional/suite_test.go
swift unfortunately uses `bind_ip` and not `bind_host`.
> Use bind_ip instead of bind_host

- controllers/swiftstorage_controller.go
If the SwiftStorage instance is created with replicas=0 - for example to adopt an existing dataplane - the network attachments will never be created due to no running pods. This resulted in a wrong status.
> Fix status update if zero replicas deployed

- controllers/swift_controller.go
- go.mod
- go.sum
Use common func to retrieve the memcached server list for a memcached instance.
> Use common memcached.GetMemcachedServerListWithInetString()

- config/manifests/bases/swift-operator.clusterserviceversion.yaml
recent changes didn't update the CSV yaml file.
This updates to match what make bundle modifies things with
> update CSV with tls

- api/bases/swift.openstack.org_swiftproxies.yaml
- api/bases/swift.openstack.org_swiftrings.yaml
- api/bases/swift.openstack.org_swifts.yaml
- api/bases/swift.openstack.org_swiftstorages.yaml
- api/v1beta1/swift_types.go
- api/v1beta1/swiftproxy_types.go
- api/v1beta1/swiftring_types.go
- api/v1beta1/swiftstorage_types.go
- config/crd/bases/swift.openstack.org_swiftproxies.yaml
- config/crd/bases/swift.openstack.org_swiftrings.yaml
- config/crd/bases/swift.openstack.org_swifts.yaml
- config/crd/bases/swift.openstack.org_swiftstorages.yaml
- config/samples/swift_v1beta1_swiftproxy.yaml
- config/samples/swift_v1beta1_swiftring.yaml
- config/samples/swift_v1beta1_swiftstorage.yaml
- controllers/swift_controller.go
- pkg/swift/const.go
- pkg/swift/templates.go
- pkg/swiftproxy/volumes.go
- pkg/swiftring/funcs.go
- pkg/swiftring/templates.go
- pkg/swiftring/volumes.go
- pkg/swiftstorage/volumes.go
- tests/kuttl/tests/basic-deploy/03-cleanup.yaml
- tests/kuttl/tests/basic-deploy_tls/02-cleanup.yaml
- tests/kuttl/tests/replication/03-force-replication.yaml
- tests/kuttl/tests/replication/04-cleanup.yaml
A couple of minor improvements to improve user-friendliness:
- removing CRD option to avoid mismatch with dataplane-operator and adoption
- better names for CM, PVC, mountpoint
> Improve user friendliness

- api/bases/swift.openstack.org_swiftproxies.yaml
- api/bases/swift.openstack.org_swifts.yaml
- api/bases/swift.openstack.org_swiftstorages.yaml
- api/v1beta1/swiftproxy_types.go
- api/v1beta1/swiftstorage_types.go
- config/crd/bases/swift.openstack.org_swiftproxies.yaml
- config/crd/bases/swift.openstack.org_swifts.yaml
- config/crd/bases/swift.openstack.org_swiftstorages.yaml
- controllers/swift_controller.go
- controllers/swiftproxy_controller.go
- controllers/swiftstorage_controller.go
- pkg/swiftproxy/templates.go
- pkg/swiftstorage/templates.go
- templates/swiftproxy/config/00-proxy-server.conf
- templates/swiftstorage/config/00-object-expirer.conf
configure tls_enabled which is either true/false depending on if the memcached instance supports tls.
Jira: [OSPRH-5283](https://issues.redhat.com//browse/OSPRH-5283)
> Configure tls_enabled for swifts cache

- controllers/swift_controller.go
Implementing the full pattern is up to each operator and will be part of a follow up.
> Set ObservedGeneration after condition init

- tests/kuttl/tests/basic-deploy/01-assert-deploy-swift.yaml
- tests/kuttl/tests/basic-deploy/03-cleanup.yaml
- tests/kuttl/tests/basic-deploy_tls/02-cleanup.yaml
- tests/kuttl/tests/replication/04-cleanup.yaml
Also improving cleanup and making tests less noisy when waiting for the rollout to be completed.
>  Add kuttl test to ensure container commands are correct

- config/manifests/bases/swift-operator.clusterserviceversion.yaml
Implements: [OSPRH-7930](https://issues.redhat.com//browse/OSPRH-7930)
> Add Required Infrastructure Annotations to CSV

- config/rbac/role.yaml
- controllers/swift_controller.go
- controllers/swiftproxy_controller.go
- controllers/swiftring_controller.go
- controllers/swiftstorage_controller.go
We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363
> Adding patch rbac perm for serviceaccounts

- api/go.mod
- api/go.sum
- controllers/swiftproxy_controller.go
- go.mod
- go.sum
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/559
Jira: [OSPRH-9991](https://issues.redhat.com//browse/OSPRH-9991)
> Update tls cert secret validation due VerifyCertSecrets() change

- controllers/swift_common.go
- controllers/swiftproxy_controller.go
Currently we get the `osp_secret` and we build the `hash` of the entire secret. If an unrelated field is added or changed, this cause a rollout of a new `swiftProxy` Pods. This change moves the `GetSecret` function call, used to compute the hash and setting it in the `envVars`, to `VerifySecret`: it checks only the `expectedFields` passed as input and it's consistent with the work already done in `Glance`, `Cinder`, and `Manila`.
Jira: https://issues.redhat.com/browse/OSPRH-8195
> Move to VerifySecret when checking the ctlplane secret

- README.md
This change fixes a small typo in the README.md that I just couldn't ignore.
> Tiny typo fix in README.md
