openstack-k8s-operators/swift-operator

api/v1beta1/swift_types.go
api/v1beta1/swiftstorage_types.go
config/crd/bases/swift.openstack.org_swifts.yaml
config/crd/bases/swift.openstack.org_swiftstorages.yaml

As we check for StorageClass="" the defaulting won't work in the webhook.

Remove the defaults for StorageClass

---

.github/workflows/build-swift-operator.yaml

The image name/repo name for swift operator doesn't have openstack in its name. Removing openstack name so that we can sort github status list correctly [1].
[1] https://github.com/gibizer/openstack-k8s-status/tree/main

Remove openstack from workflow name

---

controllers/swift_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

config/manifests/bases/swift-operator.clusterserviceversion.yaml

This should hide the neutron package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.

CSV: Set operator-type: non-standalone

---

api/go.mod
go.mod
go.sum
renovate.json

- pin k8s and controller runtime to be in sync with lib-common and configure renovate to keep the pin
- pin ocp api version to a hash in sync with lib-common instead of the nonexistent v3.9.0+incompatible tag

Add and configure renovate to pin k8s and controller-runtime for dev preview

---

config/manager/manager.yaml
config/rbac/auth_proxy_service.yaml
config/webhook/service.yaml

We now have a final form for operator controller-manager pod labeling of the format `openstack.org/operator-name: <operator name>` and are no longer relying on the inconsistent labels created by various `operator-sdk` versions.  All operators that lack this standardized pattern are being updated.

Ctrl manager labels for webhooks and logging

---

.gitignore

This file is required to build a bundle image. The file is actually maintained in the repository.

Remove config/manager/kustomization.yaml from .gitignore

---

.gitignore

This reverts commit 0a1508e7282ff0c374b5e8fae60e85f597025d08.
Reason for revert:
The file should be kept in .gitignore, so that any update made by `make bundle` is not pulled into a git commit.

Revert "Remove config/manager/kustomization.yaml from .gitignore"

---

pkg/swiftring/job.go

The variable is now a pointer, so we should make sure we use its actual data.

Fix wrong reference to RingReplicas

---

api/v1beta1/swiftproxy_types.go
api/v1beta1/swiftring_types.go
api/v1beta1/swiftstorage_types.go
config/crd/bases/swift.openstack.org_swiftproxies.yaml
config/crd/bases/swift.openstack.org_swiftrings.yaml
config/crd/bases/swift.openstack.org_swifts.yaml
config/crd/bases/swift.openstack.org_swiftstorages.yaml

... to reject any invalid values such as negative ones.
Because using 0 replicas for swift data is not a valid use case, this limits the minimum value of RingReplicas to 1 instead of 0.

Limit minimum value for Replicas spec

---

.github/create_bundle.sh
api/v1beta1/swift_types.go
config/default/manager_default_images.yaml
config/manifests/bases/swift-operator.clusterserviceversion.yaml
tests/kuttl/tests/basic-deploy/01-assert-deploy-swift.yaml

This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.
(NOTE: this currently requires a secure registry)
Jira: [OSP-26486](https://issues.redhat.com//browse/OSP-26486)

Support disconnected network environments

---

.prow_ci.env

This is used to enable USE_IMAGE_DIGESTS for prow builds

Add .prow_ci.env

---

config/manifests/bases/swift-operator.clusterserviceversion.yaml

Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)

required infra annotations for OCP 4.14+

---

config/rbac/kustomization.yaml
config/rbac/swift_configmap_update.yaml

A configmap update is required during the dataplane deployment.  The deployment will update the configmap with the actual disks to be used by Swift and their corresponding sizes, and the ring-rebalance pod will use this information to update the swift rings.

Add role and binding to update inventory configmap

---

pkg/swiftstorage/statefulset.go
pkg/swiftstorage/volumes.go

By default this should be run periodically every 5 minutes to collect async_pending data, and most often this is run as a cronjob. However, it has to be run on every node and has to use the same pvcs as the StatefulSets, thus running it within the StatefulSet itself.

Run swift-recon-cron

---

templates/swiftstorage/config/rsyncd.conf

Just running as user Swift with correct permissions doesn't require this config options and simplifies overall config.
This reverts commit c1686da7156ad4cb055e84e51bf56f6101265354.

Revert "Set uid/gid in rsyncd.conf"

---

templates/swiftproxy/config/proxy-server.conf

Sets the default reader roles to SwiftSystemReader and SwiftProjectReader, which align with the defaults from former TripleO deployments. Customizing these needs to be done by overriding config files using DefaultConfigOverwrite.

Set default reader roles for Swift

---

templates/swiftproxy/config/dispersion.conf

This allows running the tools swift-dispersion-populate and swift-dispersion-report manually if needed.

Add default dispersion.conf

---

controllers/swiftproxy_controller.go

Create the SwiftProjectReader and SwiftSystemReader default roles that can be assigned to users to provide limited read access.

Create Keystone roles for Swift RBAC

---

config/rbac/role.yaml
controllers/swiftstorage_controller.go
main.go
pkg/swiftstorage/dnsdata.go
pkg/swiftstorage/funcs.go

Storage service hostnames need to be resolvable on the dataplane nodes as well. They are used within the Swift rings to be able to allow node IP changes without updating and redistributing Swift rings.
This patch creates DNSData entries for every storage service pod, similar to [1]. It only creates DNS for the storage network, as this is the only one that should be used within the storage backend services.
There is no delete function to scale down, as we don't support scaling down for SwiftStorage instances. However, the created DNSData CRs are owned by the SwiftStorage instance, thus being deleted properly if the instance is deleted.
[1] https://github.com/openstack-k8s-operators/ovn-operator/pull/154

Add DNSData entries for SwiftStorage service pods

---

templates/swiftproxy/config/00-proxy-server.conf

This ensures feature parity with older TripleO deployments. Also change the used Keystone endpoint to public to ensure SSL is used if enabled.

Enable S3 and staticweb proxy middlewares

---

pkg/swift/funcs.go
pkg/swiftproxy/deployment.go
pkg/swiftstorage/statefulset.go

The storage and proxy services should be spread across all OCP workers if possible.

Set pod affinity to spread services across OCP workers

---

controllers/swiftring_controller.go
templates/swiftring/bin/swift-ring-rebalance.sh

Deletion of the Swift Ring ConfigMap should be prevented as far as possible. The .builder files contain data placements, which is not recoverable if lost. Thus prevent deletion except if the instance itself got deleted by using a finalizer.

Add finalizer for SwiftRing and ConfigMap

---

controllers/swiftstorage_controller.go
templates/swiftproxy/config/00-proxy-server.conf

Using 127.0.0.1 does not work in ipv6 deployments.
Also, removes other assumptions for ipv4 deployment.

Use bind_host=localhost

---

controllers/swiftring_controller.go
pkg/swiftring/funcs.go
templates/swiftring/bin/swift-ring-tool

Until now the SwiftRing instance created a ring with estimated disk sizes if PVCs and size data was not yet available. Rings were updated later once sizes were known.
However, this is no longer needed. PVCs have to be created eventually if SwiftStorage replicas > 0, thus we can requeue until these are bound. This eliminates a second rebalance with the correct values shortly after.
It also simplifies the rebalance script and removes a possible risk when changing weights for existing devices. Initially set weights are kept now, which should be the correct ones from the beginning.

Avoid second rebalance on startup

---

pkg/swiftring/funcs.go

If edpm_swift_disks is set in a nodeset both globally and per-node, only the per-node setting is used.

Fix dataplane devices in rings

---

controllers/swift_controller.go
controllers/swiftproxy_controller.go
controllers/swiftring_controller.go
controllers/swiftstorage_controller.go
templates/common/ring-sync.sh

Quite a few logging messages should not raise an error, but simply inform an user about the current state and requeue accordingly. This also avoids exponential backoffs with large requeue times due to raising the same error very quickly again. 
While doing this, improving/adding checks to requeue if dependencies are not yet ready, avoiding stacktrace logs. Cleaning this up makes users more aware of actual errors that should be investigated.

Log cleanup with necessary changes to do so

---

controllers/swiftstorage_controller.go

Once completed this was never updated when upscaling.

Fix SwiftStorage condition update

---

templates/swiftproxy/config/00-proxy-server.conf

The versioned_writes middleware was missing a setting to be enabled and exposed to the /info endpoint, and it also requires the symlink middleware to be enabled.
container_sync is not enabled in TripleO-deployments, let's keep the default unchanged and remove it.

Fix swift proxy config regression

---

config/samples/swift_v1beta1_swift.yaml
templates/common/ring-sync.sh
tests/kuttl/tests/basic-deploy/01-assert-deploy-swift.yaml

The script condition failed if there were additional files.
Adding an sample key and kuttl test to ensure there is no future regression.

Fix defaultConfig regression

---

templates/common/ring-sync.sh
templates/swiftring/bin/swift-ring-tool

This will make it possible to use projectedVolumes and remove the need for the ring-sync script and container afterwards. 
Also fixing a minor issue with the help text alongside.
Proposing this PR now to make sure the separate keys are available and preventing handling of legacy configmaps later on.

Store .ring.gz files as separate keys in ConfigMap

---

templates/swiftring/bin/swift-ring-tool

This might be on purpose if an operator created the CM and manages these manually. In that case it would be harmful to create a new .builder file and overwriting the .ring.gz file eventually.
Fixing an if-condition along the way; the swiftrings.tar.gz file would be empty if the CM key does not exist due to redirecting the output and raising an error.

Do not create new builder file automatically if ring.gz does exist

---

api/bases/swift.openstack.org_swifts.yaml
api/go.mod
api/go.sum
api/v1beta1/swift_types.go
config/crd/bases/swift.openstack.org_swifts.yaml
controllers/swift_controller.go
controllers/swiftproxy_controller.go
controllers/swiftring_controller.go
controllers/swiftstorage_controller.go
go.mod
go.sum

This patch follows the same pattern applied to the other operators, where we re-init the `conditions` at each reconcile loop. `Conditions` are re-evaluated and updated, keeping the `LastTransitionTime` for those that haven't changed (it avoids the transition from `True` to `Unknown` to `True` again).
In addition, the `observedGeneration` field is introduced, and it is used by the `openstack-operator` to check the `IsReady()` function for a particular `CR` in case a minor update is triggered. All the conditions are evaluated during the main `Reconcile` loop ( or the `reconcileNormal` function in some circumstances), hence the main `ReadyCondition` is updated within the same flow. The defer function still updates the `Resource` and `Mirror` the condition to the top-level `CR`.
Jira: …

Re-init conditions each reconcile

---

controllers/swiftstorage_controller.go
pkg/swiftstorage/statefulset.go

The `resource.MustParse` function was previously used by the operator to process the `storageSize` request provided by the top-level `Swift` `CR`. However, if the human operator passes a wrong `StorageRequest` size, a `panic()` is generated without any chance to recover. This happens because the `MustParse` implementation wraps the `ParseQuantity` function, but it returns `panic()` instead of propagating the error that can be easily caught at the operator level. This change moves away from the `MustParse` usage and rely on the `ParseQuantity` mechanism, providing an error that can be handled by the swift-operator.

Do not use MustParse to process PVC size

---

api/bases/swift.openstack.org_swiftproxies.yaml
api/bases/swift.openstack.org_swifts.yaml
api/v1beta1/swiftproxy_types.go
config/crd/bases/swift.openstack.org_swiftproxies.yaml
config/crd/bases/swift.openstack.org_swifts.yaml
config/rbac/role.yaml
controllers/swift_controller.go
controllers/swiftproxy_controller.go
main.go
pkg/swiftproxy/templates.go
templates/swiftproxy/config/00-proxy-server.conf

The Ceilometer middleware sends notifications using RabbitMQ, thus creating a user and secret to configure the middleware.

Configure Ceilometer middleware

---

templates/swiftproxy/config/httpd.conf

Enable ProxyPreserveHost to preserve the request hostname. The hostname is used by the s3api middleware to compute and verify the signature. Without this setting it is simply using localhost:8081 which never matches.
Jira: [OSPRH-5835](https://issues.redhat.com//browse/OSPRH-5835)

Fix httpd proxy configuration for s3api

---

pkg/swiftstorage/statefulset.go

Looks like the same command is used for multiple sidecar containers. This change is supposed to fix the process run within the sidecar containers.

Fix some container commands

---

config/samples/swift_v1beta1_swift.yaml
tests/kuttl/tests/basic-deploy/01-assert-deploy-swift.yaml
tests/kuttl/tests/customization/00-deps.yaml
tests/kuttl/tests/customization/01-assert-deploy-swift.yaml
tests/kuttl/tests/customization/01-deploy-swift.yaml
tests/kuttl/tests/customization/02-assert-objects.yaml
tests/kuttl/tests/customization/02-create-objects.yaml
tests/kuttl/tests/customization/03-assert-ceilometer.yaml
tests/kuttl/tests/customization/03-test-ceilometer.yaml
tests/kuttl/tests/customization/04-assert-encryption.yaml
tests/kuttl/tests/customization/04-test-encryption.yaml
tests/kuttl/tests/customization/05-assert-containersharder.yaml
tests/kuttl/tests/customization/05-test-containersharder.yaml
tests/kuttl/tests/customization/06-assert-customization.yaml
tests/kuttl/tests/customization/06-test-customization.yaml
tests/kuttl/tests/customization/07-assert-custom-swiftconf.yaml
tests/kuttl/tests/customization/07-test-custom-swiftconf.yaml
tests/kuttl/tests/customization/08-assert-ringsettings.yaml
tests/kuttl/tests/customization/08-test-ringsettings.yaml
tests/kuttl/tests/customization/09-cleanup.yaml
tests/kuttl/tests/customization/09-errors-cleanup.yaml
tests/kuttl/tests/customization/deploy/kustomization.yaml
tests/kuttl/tests/customization/deploy/swift-conf-secrect.yaml

Adds a bunch of tests to verify customization settings. Most of these settings do exist in a similar way in TripleO, thus making sure these options do still work.
- Add kuttl test to verify ceilometermiddleware integration
- Add kuttl test to verify object encryption using Barbican
- Add kuttl test to verify container sharder enablement
- Add kuttl test to verify config customization
- Add kuttl test to verify custom swift.conf
- Add kuttl test to verify ring settings
The last test needs #201 to be merged first.

More kuttl tests to verify Barbican, Ceilometer and other customizations

---

api/bases/swift.openstack.org_swiftproxies.yaml
api/bases/swift.openstack.org_swiftrings.yaml
api/bases/swift.openstack.org_swiftstorages.yaml
api/v1beta1/swiftproxy_types.go
api/v1beta1/swiftring_types.go
api/v1beta1/swiftstorage_types.go
config/crd/bases/swift.openstack.org_swiftproxies.yaml
config/crd/bases/swift.openstack.org_swiftrings.yaml
config/crd/bases/swift.openstack.org_swiftstorages.yaml
controllers/swift_controller.go
controllers/swiftproxy_controller.go
controllers/swiftring_controller.go
controllers/swiftstorage_controller.go

This patch  aligns the swift-operator with the current ObservedGeneration pattern proposed for other operators.
In particular:
1. it adds `observedGeneration` to the sub custom resources
2. it proposes to bump the `observedGeneration` at the beginning of the reconciliation loop (knative/serving#4937)
3. it checks, at the top level, if `ObservedGeneration` matches with the `metadata.generation` assigned to the `subCR(s)`
4. before marking the `DeploymentReadyCondition` as `True`, the `ObservedGeneration` is compared with the `Generation` of the `Deployment`

Add ObservedGeneration to the sub Resources

---

.pre-commit-config.yaml
controllers/swift_controller.go
controllers/swiftproxy_controller.go
controllers/swiftstorage_controller.go
pkg/swiftstorage/dnsdata.go
pkg/swiftstorage/networkpolicy.go
tests/functional/suite_test.go

This patch moves the pre-commit-config to golangci-lint-full and clean up most of the code leftovers.
In particular:
- unused func params are removed
- better use of ctx context.Context
- fix revive error for envTests

Move to golangci-lint-full

---

pkg/swiftring/funcs.go
templates/swiftring/bin/swift-ring-tool

The nodename will be used later on to improve rebalancing to avoid assigning multiple replicas to the same node. Adding this data now to avoid adding a ring upgrade mechanism later on; once devices are added to the rings they won't be changed anymore by the operator.

Add nodename as metadata to Swift rings

---

controllers/swiftproxy_controller.go
controllers/swiftring_controller.go
controllers/swiftstorage_controller.go

Some of those calls for newInstance was directly redundant as the
self finalizer condition already handled the newInstance case as well.
Other places used explicit status updates instead of relying on the
deferred PatchInstance call. In general explicit update is dangerous
as it only updates either the main resource or the status subresource,
but then the result of the API call is used to update the instance
variable overriding any not persisted in memory updates.

Remove explicit instance Update calls

---

pkg/swiftring/funcs.go
templates/swiftring/bin/swift-ring-tool

Fixes an issue if the Pod nodename is not yet set, for example if the Pod is already created but not yet assigned to a node. In that case the swift-ring-builder will fail with "error: --meta option requires 1 argument".

Fix unscheduled podname issue when building Swift rings

---

config/rbac/role.yaml
controllers/swiftstorage_controller.go

Commit a987062 restricted the RBAC permissions for Pods to Get and List operations, as these are the only ones required by the swift-operator itself. However, Get/List operations are using an informerCache, which itself sets up a Watch to the objects. Without the required watch permission this throws an error in the operator log like this:
Failed to watch *v1.Pod: unknown (get pods)
Example: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_swift-operator/213/pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl/1783865524250218496/artifacts/swift-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3b72ed0 …

Fix Pod watch RBAC error

---

api/go.mod
api/go.sum
api/v1beta1/swift_webhook.go
go.mod
go.sum

Can also be called from the openstack-operator webhook on the SwiftSpecCore, like for other operators in [1].
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505
[1] https://github.com/openstack-k8s-operators/openstack-operator/blob/d2703d3a321c979dacaca95b5d4a634bf116e0db/apis/core/v1beta1/openstackcontrolplane_webhook.go#L181

Add webhook to validate service override endpoint type

---

controllers/swiftring_controller.go
templates/swiftring/bin/swift-ring-tool

The swift-ring finalizer is created by a curl API request and not using lib-common. This patch standardizes the finalizer name by adding the missing domain name.
Related: https://github.com/openstack-k8s-operators/lib-common/pull/519

Standardize swift-ring finalizer name

---

api/v1beta1/swift_webhook.go

If the `OpenStackControlPlane` CR's `spec.swift.template` section is missing, trying to `oc patch` it fails due to a nil-pointer on the server side.
Jira: https://issues.redhat.com/browse/OSPRH-8705

[OSPRH-8705] Fix SwiftStorage replicas update nil pointer

---

controllers/swiftring_controller.go

If a rebalance is needed and the job has to re-run, it will be deleted first. Deletes are executed using a background deletion policy, thus a deleted job might still exist and if the operator tries to re-create it, it will immediately become succesful (and not executed at all).
This commit changes the behaviour to reconcile again if the job does exist.

Fix race condition if ring rebalance is needed

---

controllers/swiftproxy_controller.go
controllers/swiftstorage_controller.go

Returning a non-nil err with a RequeueAfter result causes k8s to discard the explicit requeue and wait much longer than desired.

Log 'not found' error instead of returning it if using RequeueAfter

---

controllers/swiftproxy_controller.go

It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```

Make sure to log error in findObjectsForSrc()

---

controllers/swiftstorage_controller.go

Swift uses the storage network currently, but the correct network should be the storagemgmt one. This fix prefers the storagemgmt and falls back to storage to prevent failures in already deployed environments.

Use storagemgmt network by default if defined

---

controllers/swift_controller.go

If the ring file configmap is created without an owner set, updating and adding the ownerRef fails because this requires the delete verb. This happens for example when adopting an existing deployment.
Jira: [OSPRH-11016](https://issues.redhat.com//browse/OSPRH-11016)

Fix swift-ring-files ConfigMap update issue

---

templates/swiftring/bin/swift-ring-tool

This change shows the response body if the ring ConfigMap get/update requests fail which helps to debug deployment errors more easily.

Be more verbose on ring ConfigMap update errors

---

controllers/swiftproxy_controller.go
controllers/swiftstorage_controller.go

Zero replicas are used when adopting a dataplane, and in that case the SwiftStorage instance will never reach the Ready state because there are no pods running that can be attached to a network.
This commit fixes the condition update for the SwiftStorage and SwiftProxy instance as well.

Fix NetworkReadyCondition if using zero replicas

---

api/go.mod
api/go.sum
controllers/swiftproxy_controller.go
controllers/swiftstorage_controller.go
go.mod
go.sum

For BGP setup there is the need to set the default gateway to the additional interface defined via the multus annotations. To allow this a user can configure `ipam.gateway` in the NAD. EnsureNetworksAnnotation() will override the pod network default route by reading the NAD. If `ipam.gateway` is defined and not "", it gets set on the networks annotation as the `default-route`.
Jira: https://issues.redhat.com/browse/OSPRH-8680
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/579

Use new nad.EnsureNetworksAnnotation() func to get NAD annotations

---

templates/swiftproxy/config/httpd.conf

As done for neutron-operator [1], adding a conditional to set the header only if it is empty.
This is required in case we deploy with tls.podlevel=false and tls.ingress=true.
Jira: https://issues.redhat.com/browse/OSPRH-12375
[1] openstack-k8s-operators/neutron-operator#453

[httpd] Set X-Forwarded-Proto only if empty

---

templates/swiftring/bin/swift-ring-tool

The ring rebalance uses the hostname/IP of the device to distribute replicas across nodes. However, since there is one unique hostname per pod and multiple pods might be running on the same hardware node, this does not guarantee replica assignment to different nodes when using PVs as backend and using multiple PVs per node.
To ensure devices are distributed within the cluster as far from each other as possible, the underlying nodename needs to be used when rebalancing.
The node name of each PVs is already stored within the metadata field of the Swift ring. This change makes use of this when rebalancing: it swaps the IP and meta fields, rebalances (now using the actual node name itself and not the pod name) and afterwards swaps back meta and IP field. Afterwards write_ring is called to …

Add node-awareness to ring rebalance when using PVs

---

api/go.mod
api/go.sum
api/v1beta1/swift_webhook.go
api/v1beta1/swiftproxy_types.go
api/v1beta1/swiftstorage_types.go
go.mod
go.sum

This patch is a follow up of [1] in the validation `webhook` area. It enhances the validation workflow and it aims to complete the pattern by distributing the `ValidateTopology` logic across the `API` instances.
It is based on [2] and the key improvements include:
- `Distributed validation`: it provides a `ValidateTopology` function across all API instances, ensuring consistent validation throughout the system
- `Optimized validation calls`: it refines how validation is triggered and reduce code duplication; it still requires a basic struct refactor to fully de-duplicate the existing functions, but it can be done as part of a follow up
This patch leverages the centralized topology validator introduced in `infra-operator` [2].
Jira: https://issues.redhat.com/browse/OSPRH-14626
[1] …

Complete webhook validation for topology references

---

api/go.mod
api/go.sum
controllers/swift_common.go
go.mod
go.sum

This patch removes the need of using `GetLastAppliedTopologyRef` to build a `topologyRef` used by `EnsureServiceTopology` provided by infra-operator. In particular, we can now blindly pass `instance.Status.LastAppliedTopologyRef`, and checking that is not nil is deferred to the infra-operator logic [1]. This change also allows to deduplicate most of the common code present in all operators.
Depends-On: https://github.com/openstack-k8s-operators/infra-operator/pull/367
Jira: https://issues.redhat.com/browse/OSPRH-15412
[1] https://github.com/openstack-k8s-operators/infra-operator/pull/367

Optmize handling topology logic

---

controllers/swiftproxy_controller.go
go.mod
go.sum

Adds watches of the Nova controller on the KeystoneAPI status to reconcile if e.g. the endpoint list changes. This triggers setting the new KeystoneAuthURL on the sub components to update their configuration.
Depends-On: https://github.com/openstack-k8s-operators/keystone-operator/pull/591
Jira: [OSPRH-16994](https://issues.redhat.com//browse/OSPRH-16994)

Watch KeystoneAPI status updates to reconcile

---

controllers/swift_controller.go
controllers/swiftproxy_controller.go
controllers/swiftring_controller.go
controllers/swiftstorage_controller.go

Currently we use deferred call to always update the status field when Reconcile call exits, which seems correct for any other error except Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-16938](https://issues.redhat.com//browse/OSPRH-16938)

Do not update status when reconciler exits due to panic

---

api/bases/swift.openstack.org_swiftrings.yaml
api/bases/swift.openstack.org_swifts.yaml
api/v1beta1/swiftring_types.go
config/crd/bases/swift.openstack.org_swiftrings.yaml
config/crd/bases/swift.openstack.org_swifts.yaml
controllers/swift_controller.go
hack/crd-schema-checker.sh

This makes it possible to disable automatic ring management if needed. Depending on the cluster this might be needed, for example when using storage policies or operating large clusters that are managed manually.
JIRA: [OSPRH-11686](https://issues.redhat.com//browse/OSPRH-11686)

Add option to disable ring init/rebalance job

---

controllers/swiftproxy_controller.go
pkg/swiftproxy/deployment.go
pkg/swiftproxy/templates.go
templates/swiftproxy/config/00-proxy-server.conf

This change adds additional volume/volumemounts if memcached has been configured for MTLS auth, and adds the necessary parameters for the swift cache middleware to set the tls context.

Add MTLS certificates and enable mtls auth

---

tests/functional/suite_test.go

This change update the suite_test SetupWithManager function to use other Swift controller resources, instead of using single SwiftController.

Fix suite_test
